[package]
name = "zip-extensions"
version = "0.6.1"
authors = ["Matthias Friedrich <rushiblegit@gmail.com>"]
edition = "2018"
description = "An extension crate for zip."
readme = "README.md"
repository = "https://github.com/matzefriedrich/zip-extensions-rs"
license = "MIT"
keywords = ["zip", "archive"]
exclude = [
    "**/*.yml",
    "**/*.json",
    ".gitignore"
]

[dependencies]
zip = "0.5"
