[package]
name = "zip-extensions"
version = "0.8.4"
authors = ["Matthias Friedrich <rushiblegit@gmail.com>"]
edition = "2021"
description = "An extension crate for zip."
readme = "README.md"
repository = "https://github.com/matzefriedrich/zip-extensions-rs"
license = "MIT"
keywords = ["zip", "archive", "compression"]
exclude = ["**/*.yml", "**/*.json", ".gitignore"]

[dependencies]
zip = { version = "6.0", default-features = false }

[features]
aes-crypto = ["zip/aes-crypto"]
bitstream-io = ["zip/bitstream-io"]
bzip2 = ["zip/bzip2"]
chrono = ["zip/chrono"]
deflate = ["zip/deflate"]
deflate64 = ["zip/deflate64"]
deflate-flate2 = ["zip/deflate-flate2"]
deflate-flate2-zlib = ["zip/deflate-flate2-zlib"]
deflate-flate2-zlib-rs = ["zip/deflate-flate2-zlib-rs"]
deflate-zopfli = ["zip/deflate-zopfli"]
getrandom = ["zip/getrandom"]
hmac = ["zip/hmac"]
jiff-02 = ["zip/jiff-02"]
legacy-zip = ["zip/legacy-zip"]
lzma = ["zip/lzma"]
lzma-static = ["zip/lzma-static"]
nt-time = ["zip/nt-time"]
pbkdf2 = ["zip/pbkdf2"]
ppmd = ["zip/ppmd"]
sha1 = ["zip/sha1"]
time = ["zip/time"]
unreserved = ["zip/unreserved"]
xz = ["zip/xz"]
xz-static = ["zip/xz-static"]
zeroize = ["zip/zeroize"]
zstd = ["zip/zstd"]

default = [
    "aes-crypto",
    "bzip2",
    "deflate",
    "deflate64",
    "lzma",
    "ppmd",
    "time",
    "xz",
    "zstd",
]
